// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type BlockChildrenResponse struct {
	HasMore    bool            `json:"has_more"`
	NextCursor string          `json:"next_cursor"`
	Object     string          `json:"object"`
	Results    json.RawMessage `json:"results"`
}

type BlockResponse struct {
	Archived       bool            `json:"archived"`
	CreatedTime    string          `json:"created_time"`
	HasChildren    bool            `json:"has_children"`
	Id             string          `json:"id"`
	LastEditedTime string          `json:"last_edited_time"`
	Object         string          `json:"object"`
	Properties     json.RawMessage `json:"properties"`
	Type           string          `json:"type"`
}

type CreatePageRequest struct {
	Children   json.RawMessage `json:"children"`
	Parent     json.RawMessage `json:"parent"`
	Properties json.RawMessage `json:"properties"`
}

type PagePropertyResponse struct {
	HasMore    bool            `json:"has_more"`
	Id         string          `json:"id"`
	NextCursor string          `json:"next_cursor"`
	Object     string          `json:"object"`
	Property   json.RawMessage `json:"property"`
	Type       string          `json:"type"`
}

type PageResponse struct {
	CreatedTime    string          `json:"created_time"`
	Id             string          `json:"id"`
	LastEditedTime string          `json:"last_edited_time"`
	Object         string          `json:"object"`
	Parent         json.RawMessage `json:"parent"`
	Properties     json.RawMessage `json:"properties"`
	Url            string          `json:"url"`
}

type SearchRequest struct {
	Filter      json.RawMessage `json:"filter"`
	PageSize    int             `json:"page_size"`
	Query       string          `json:"query"`
	Sort        json.RawMessage `json:"sort"`
	StartCursor string          `json:"start_cursor"`
}

type SearchResponse struct {
	HasMore    bool            `json:"has_more"`
	NextCursor string          `json:"next_cursor"`
	Results    json.RawMessage `json:"results"`
}

type UpdateBlockChildrenRequest struct {
	Children json.RawMessage `json:"children"`
}

type UpdateBlockRequest struct {
	Properties json.RawMessage `json:"properties"`
	Type       string          `json:"type"`
}

type UpdatePageRequest struct {
	Archived   bool            `json:"archived"`
	Properties json.RawMessage `json:"properties"`
}
