// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"notion-pp-cli/internal/cli"
	"notion-pp-cli/internal/client"
	"notion-pp-cli/internal/cliutil"
	"notion-pp-cli/internal/config"
	"notion-pp-cli/internal/mcp/cobratree"
	"notion-pp-cli/internal/store"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("blocks_delete",
			mcplib.WithDescription("Delete a block using its ID. Required: block_id. Returns the BlockResponse. Destructive."),
			mcplib.WithString("block_id", mcplib.Required(), mcplib.Description("The ID of the block to delete.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/v1/blocks/{block_id}", false, false, nil, []mcpParamBinding{{PublicName: "block_id", WireName: "block_id", Location: "path"}}, []string{"block_id"}),
	)
	s.AddTool(
		mcplib.NewTool("blocks_retrieve",
			mcplib.WithDescription("Retrieve a block object using its ID. Required: block_id. Returns the BlockResponse."),
			mcplib.WithString("block_id", mcplib.Required(), mcplib.Description("The ID of the block to retrieve.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/blocks/{block_id}", true, false, nil, []mcpParamBinding{{PublicName: "block_id", WireName: "block_id", Location: "path"}}, []string{"block_id"}),
	)
	s.AddTool(
		mcplib.NewTool("blocks_update",
			mcplib.WithDescription("Update a block's properties. Required: block_id, type. Optional: properties. Returns the updated BlockResponse."),
			mcplib.WithString("block_id", mcplib.Required(), mcplib.Description("The ID of the block to update.")),
			mcplib.WithString("properties", mcplib.Description("The properties to update for the block.")),
			mcplib.WithString("type", mcplib.Required(), mcplib.Description("The type of block (e.g., paragraph, image).")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/v1/blocks/{block_id}", false, false, nil, []mcpParamBinding{{PublicName: "block_id", WireName: "block_id", Location: "path"}, {PublicName: "properties", WireName: "properties", Location: "body"}, {PublicName: "type", WireName: "type", Location: "body"}}, []string{"block_id"}),
	)
	s.AddTool(
		mcplib.NewTool("children_retrieve-block",
			mcplib.WithDescription("Retrieve the children of a block. Required: block_id. Optional: start_cursor, page_size. Returns the BlockChildrenResponse."),
			mcplib.WithString("block_id", mcplib.Required(), mcplib.Description("The ID of the block whose children are to be retrieved.")),
			mcplib.WithString("start_cursor", mcplib.Description("Pagination cursor for fetching the next set of results.")),
			mcplib.WithNumber("page_size", mcplib.Description("The number of results to retrieve per page (default is 100).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/blocks/{block_id}/children", true, false, nil, []mcpParamBinding{{PublicName: "block_id", WireName: "block_id", Location: "path"}, {PublicName: "start_cursor", WireName: "start_cursor", Location: "query"}, {PublicName: "page_size", WireName: "page_size", Location: "query"}}, []string{"block_id"}),
	)
	s.AddTool(
		mcplib.NewTool("children_update-block",
			mcplib.WithDescription("Update the children of a block. Required: block_id, children. Returns the updated BlockChildrenResponse."),
			mcplib.WithString("block_id", mcplib.Required(), mcplib.Description("The ID of the block to update.")),
			mcplib.WithString("children", mcplib.Required(), mcplib.Description("The list of block children to update.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/v1/blocks/{block_id}/children", false, false, nil, []mcpParamBinding{{PublicName: "block_id", WireName: "block_id", Location: "path"}, {PublicName: "children", WireName: "children", Location: "body"}}, []string{"block_id"}),
	)
	s.AddTool(
		mcplib.NewTool("notion-search_search",
			mcplib.WithDescription("Search for pages, databases, and other objects within a Notion workspace. Optional: filter, page_size, query (plus 2 more). Returns the new SearchResponse."),
			mcplib.WithString("filter", mcplib.Description("Filter")),
			mcplib.WithNumber("page_size", mcplib.Description("Number of results to return per page.")),
			mcplib.WithString("query", mcplib.Description("The text to search for.")),
			mcplib.WithString("sort", mcplib.Description("Sort")),
			mcplib.WithString("start_cursor", mcplib.Description("Pagination cursor for the start of the search results.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1/search", true, false, nil, []mcpParamBinding{{PublicName: "filter", WireName: "filter", Location: "body"}, {PublicName: "page_size", WireName: "page_size", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "sort", WireName: "sort", Location: "body"}, {PublicName: "start_cursor", WireName: "start_cursor", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pages_create",
			mcplib.WithDescription("Create a new page in a Notion database. Required: parent, properties. Optional: children. Returns the new PageResponse."),
			mcplib.WithString("children", mcplib.Description("List of block objects for the page content.")),
			mcplib.WithString("parent", mcplib.Required(), mcplib.Description("Parent")),
			mcplib.WithString("properties", mcplib.Required(), mcplib.Description("The properties of the page.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1/pages", false, false, nil, []mcpParamBinding{{PublicName: "children", WireName: "children", Location: "body"}, {PublicName: "parent", WireName: "parent", Location: "body"}, {PublicName: "properties", WireName: "properties", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pages_retrieve",
			mcplib.WithDescription("Retrieve a page object using the page ID. Required: page_id. Returns the PageResponse."),
			mcplib.WithString("page_id", mcplib.Required(), mcplib.Description("The ID of the page to retrieve.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/pages/{page_id}", true, false, nil, []mcpParamBinding{{PublicName: "page_id", WireName: "page_id", Location: "path"}}, []string{"page_id"}),
	)
	s.AddTool(
		mcplib.NewTool("pages_update",
			mcplib.WithDescription("Update the properties of a specific page by its ID. Required: page_id, properties. Optional: archived. Returns the updated PageResponse."),
			mcplib.WithString("page_id", mcplib.Required(), mcplib.Description("The ID of the page to update.")),
			mcplib.WithBoolean("archived", mcplib.Description("Whether to archive the page.")),
			mcplib.WithString("properties", mcplib.Required(), mcplib.Description("The properties to update for the page.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/v1/pages/{page_id}", false, false, nil, []mcpParamBinding{{PublicName: "page_id", WireName: "page_id", Location: "path"}, {PublicName: "archived", WireName: "archived", Location: "body"}, {PublicName: "properties", WireName: "properties", Location: "body"}}, []string{"page_id"}),
	)
	s.AddTool(
		mcplib.NewTool("pages_properties_retrieve-page-property",
			mcplib.WithDescription("Retrieve a page property using the page ID and property ID. Required: page_id, property_id. Returns the PagePropertyResponse."),
			mcplib.WithString("page_id", mcplib.Required(), mcplib.Description("The ID of the page.")),
			mcplib.WithString("property_id", mcplib.Required(), mcplib.Description("The ID of the property to retrieve.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/pages/{page_id}/properties/{property_id}", true, false, nil, []mcpParamBinding{{PublicName: "page_id", WireName: "page_id", Location: "path"}, {PublicName: "property_id", WireName: "property_id", Location: "path"}}, []string{"page_id", "property_id"}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// --- Amendment 1: magic-moment command tools ---------------------------
	// The hand-authored extended-markdown writer, annotation-aware local
	// mirror, and compound workflows, surfaced as named typed tools. Each
	// shells out to the companion CLI command, which is mcp:hidden so the
	// runtime mirror below does not double-register it under a generated name.
	s.AddTool(
		mcplib.NewTool("format-write-page",
			mcplib.WithDescription("Render an extended-markdown document to a Notion page, preserving the block-level color and per-run annotation fidelity (bold/italic/underline/strike/code, text & background colors, callout icons) the official Notion MCP drops. Required: page_id. Supply md or from-markdown. mode: append (default) or replace."),
			mcplib.WithString("page_id", mcplib.Required(), mcplib.Description("Target page ID.")),
			mcplib.WithString("md", mcplib.Description("Inline extended-markdown source text.")),
			mcplib.WithString("from-markdown", mcplib.Description("Path to an extended-markdown file to render.")),
			mcplib.WithString("mode", mcplib.Description("append (default) or replace (archives existing blocks first).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeCLITool([]string{"format", "write-page"}, []string{"page_id"}, nil),
	)
	s.AddTool(
		mcplib.NewTool("format-update-block",
			mcplib.WithDescription("Re-style an existing block's formatting in place (block color, per-run annotations, callout icon, to_do checked state) without retyping its text. Required: block_id."),
			mcplib.WithString("block_id", mcplib.Required(), mcplib.Description("Target block ID.")),
			mcplib.WithString("color", mcplib.Description("Set the block-level color (e.g. blue, red_bg).")),
			mcplib.WithString("recolor", mcplib.Description("Set annotations.color on every existing run (keeps the text).")),
			mcplib.WithString("set", mcplib.Description("Enable annotations on every run: bold,italic,underline,strike,code.")),
			mcplib.WithString("unset", mcplib.Description("Disable annotations on every run.")),
			mcplib.WithString("icon", mcplib.Description("Set a callout icon (emoji or shortcode, e.g. rocket).")),
			mcplib.WithString("md", mcplib.Description("Replace the block's rich text from extended markdown.")),
			mcplib.WithBoolean("check", mcplib.Description("Mark a to_do block checked.")),
			mcplib.WithBoolean("uncheck", mcplib.Description("Mark a to_do block unchecked.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeCLITool([]string{"format", "update"}, []string{"block_id"}, nil),
	)
	s.AddTool(
		mcplib.NewTool("format-read-page",
			mcplib.WithDescription("Read a page's full block tree and render it back to the extended-markdown dialect, round-tripping block-level color and per-run annotations (the inverse of format-write-page). Required: page_id."),
			mcplib.WithString("page_id", mcplib.Required(), mcplib.Description("Page ID to read.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeCLITool([]string{"format", "read-page"}, []string{"page_id"}, nil),
	)
	s.AddTool(
		mcplib.NewTool("sync-database",
			mcplib.WithDescription("Sync Notion API data into the local SQLite store so the search-local and sql tools can query it offline. No remote mutation. Optional: resources (comma-separated), full, since (e.g. 7d)."),
			mcplib.WithString("resources", mcplib.Description("Comma-separated resource types to sync (default: all).")),
			mcplib.WithBoolean("full", mcplib.Description("Full resync, ignoring the previous checkpoint.")),
			mcplib.WithString("since", mcplib.Description("Incremental window, e.g. 7d, 24h, 1w.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		makeCLITool([]string{"sync"}, nil, nil),
	)
	s.AddTool(
		mcplib.NewTool("sync-page",
			mcplib.WithDescription("Mirror one page's full block tree into local SQLite with per-run color/annotation columns (tables: pages, blocks, rich_text; views: colored_text, block_palette) so format sql can query formatting. No remote mutation. Required: page_id."),
			mcplib.WithString("page_id", mcplib.Required(), mcplib.Description("Page ID to mirror.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		makeCLITool([]string{"format", "mirror"}, []string{"page_id"}, nil),
	)
	s.AddTool(
		mcplib.NewTool("search-local",
			mcplib.WithDescription("Full-text search across locally synced data (SQLite FTS5). Faster than paginating list endpoints and works offline. Run sync-database first. Required: query."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (FTS5 syntax: AND, OR, NOT, quoted phrases).")),
			mcplib.WithNumber("limit", mcplib.Description("Maximum results to return.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		makeCLITool([]string{"search"}, []string{"query"}, map[string]string{"data-source": "local"}),
	)
	s.AddTool(
		mcplib.NewTool("workflow-run",
			mcplib.WithDescription("Run the compound archive workflow: fetch all syncable resources from the API into the local SQLite store for offline search and analysis. No remote mutation. Optional: full."),
			mcplib.WithBoolean("full", mcplib.Description("Full re-archive, ignoring previous sync state.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		makeCLITool([]string{"workflow", "archive"}, nil, nil),
	)

	// --- Amendment 2: Notion REST parity tools -----------------------------
	// Public Notion endpoints the official Notion MCP exposes but this CLI's
	// generated spec (blocks/children/pages/search only) omitted: databases,
	// comments, users, and page move/duplicate. These call the API directly
	// via makeAPIHandler, matching the typed endpoint tools above.
	s.AddTool(
		mcplib.NewTool("databases-create",
			mcplib.WithDescription("Create a database under a parent page. Required: parent, properties (the column schema). Optional: title. Returns the new database."),
			mcplib.WithString("parent", mcplib.Required(), mcplib.Description("Parent reference, e.g. {\"type\":\"page_id\",\"page_id\":\"...\"}.")),
			mcplib.WithString("title", mcplib.Description("Database title as a rich-text array.")),
			mcplib.WithString("properties", mcplib.Required(), mcplib.Description("Property-schema object defining the database columns.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1/databases", false, false, nil, []mcpParamBinding{{PublicName: "parent", WireName: "parent", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}, {PublicName: "properties", WireName: "properties", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("databases-retrieve",
			mcplib.WithDescription("Retrieve a database's metadata and property schema. Required: database_id."),
			mcplib.WithString("database_id", mcplib.Required(), mcplib.Description("The ID of the database to retrieve.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/databases/{database_id}", true, false, nil, []mcpParamBinding{{PublicName: "database_id", WireName: "database_id", Location: "path"}}, []string{"database_id"}),
	)
	s.AddTool(
		mcplib.NewTool("databases-update",
			mcplib.WithDescription("Update a database's title, description, or property schema. Required: database_id. Optional: title, description, properties."),
			mcplib.WithString("database_id", mcplib.Required(), mcplib.Description("The ID of the database to update.")),
			mcplib.WithString("title", mcplib.Description("New title as a rich-text array.")),
			mcplib.WithString("description", mcplib.Description("New description as a rich-text array.")),
			mcplib.WithString("properties", mcplib.Description("Property-schema changes.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/v1/databases/{database_id}", false, false, nil, []mcpParamBinding{{PublicName: "database_id", WireName: "database_id", Location: "path"}, {PublicName: "title", WireName: "title", Location: "body"}, {PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "properties", WireName: "properties", Location: "body"}}, []string{"database_id"}),
	)
	s.AddTool(
		mcplib.NewTool("databases-query",
			mcplib.WithDescription("Query a database's rows with optional filter and sorts. Required: database_id. Optional: filter, sorts, start_cursor, page_size. Returns matching pages."),
			mcplib.WithString("database_id", mcplib.Required(), mcplib.Description("The ID of the database to query.")),
			mcplib.WithString("filter", mcplib.Description("Notion filter object.")),
			mcplib.WithString("sorts", mcplib.Description("Sort array.")),
			mcplib.WithString("start_cursor", mcplib.Description("Pagination cursor.")),
			mcplib.WithNumber("page_size", mcplib.Description("Results per page (max 100).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1/databases/{database_id}/query", true, false, nil, []mcpParamBinding{{PublicName: "database_id", WireName: "database_id", Location: "path"}, {PublicName: "filter", WireName: "filter", Location: "body"}, {PublicName: "sorts", WireName: "sorts", Location: "body"}, {PublicName: "start_cursor", WireName: "start_cursor", Location: "body"}, {PublicName: "page_size", WireName: "page_size", Location: "body"}}, []string{"database_id"}),
	)
	s.AddTool(
		mcplib.NewTool("comments-list",
			mcplib.WithDescription("List unresolved comments on a block or page. Required: block_id. Optional: start_cursor, page_size."),
			mcplib.WithString("block_id", mcplib.Required(), mcplib.Description("Block or page ID to list comments for.")),
			mcplib.WithString("start_cursor", mcplib.Description("Pagination cursor.")),
			mcplib.WithNumber("page_size", mcplib.Description("Results per page.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/comments", true, false, nil, []mcpParamBinding{{PublicName: "block_id", WireName: "block_id", Location: "query"}, {PublicName: "start_cursor", WireName: "start_cursor", Location: "query"}, {PublicName: "page_size", WireName: "page_size", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("comments-create",
			mcplib.WithDescription("Create a comment. Provide rich_text plus either parent ({\"page_id\":...}) to start a thread, or discussion_id to reply to an existing one."),
			mcplib.WithString("rich_text", mcplib.Required(), mcplib.Description("Comment body as a rich-text array.")),
			mcplib.WithString("parent", mcplib.Description("Parent reference to start a new comment thread, e.g. {\"page_id\":\"...\"}.")),
			mcplib.WithString("discussion_id", mcplib.Description("Existing discussion thread to reply to.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1/comments", false, false, nil, []mcpParamBinding{{PublicName: "parent", WireName: "parent", Location: "body"}, {PublicName: "discussion_id", WireName: "discussion_id", Location: "body"}, {PublicName: "rich_text", WireName: "rich_text", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users-list",
			mcplib.WithDescription("List all users in the workspace. Optional: start_cursor, page_size."),
			mcplib.WithString("start_cursor", mcplib.Description("Pagination cursor.")),
			mcplib.WithNumber("page_size", mcplib.Description("Results per page.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/users", true, false, nil, []mcpParamBinding{{PublicName: "start_cursor", WireName: "start_cursor", Location: "query"}, {PublicName: "page_size", WireName: "page_size", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users-retrieve",
			mcplib.WithDescription("Retrieve a user by ID. Required: user_id."),
			mcplib.WithString("user_id", mcplib.Required(), mcplib.Description("The ID of the user to retrieve.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/users/{user_id}", true, false, nil, []mcpParamBinding{{PublicName: "user_id", WireName: "user_id", Location: "path"}}, []string{"user_id"}),
	)
	s.AddTool(
		mcplib.NewTool("users-me",
			mcplib.WithDescription("Retrieve the bot user associated with the current integration token."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/users/me", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pages-move",
			mcplib.WithDescription("Move a page to a new parent (page or database) by updating its parent reference. Required: page_id, parent."),
			mcplib.WithString("page_id", mcplib.Required(), mcplib.Description("The ID of the page to move.")),
			mcplib.WithString("parent", mcplib.Required(), mcplib.Description("New parent, e.g. {\"type\":\"page_id\",\"page_id\":\"...\"} or {\"database_id\":\"...\"}.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/v1/pages/{page_id}", false, false, nil, []mcpParamBinding{{PublicName: "page_id", WireName: "page_id", Location: "path"}, {PublicName: "parent", WireName: "parent", Location: "body"}}, []string{"page_id"}),
	)
	s.AddTool(
		mcplib.NewTool("pages-duplicate",
			mcplib.WithDescription("Duplicate a page: copies its properties and full block tree into a new page (compound workflow — Notion has no single duplicate endpoint). Required: page_id. Optional: parent (target parent; defaults to the source's parent)."),
			mcplib.WithString("page_id", mcplib.Required(), mcplib.Description("The ID of the page to duplicate.")),
			mcplib.WithString("parent", mcplib.Description("Target parent for the copy; defaults to the source page's parent.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		handleDuplicatePage,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

// makeCLITool builds an MCP tool handler that shells out to a hand-authored
// companion-CLI command (the magic-moment writer/mirror/workflow commands,
// which carry richer local logic than a single REST endpoint). positionals are
// appended in order as bare arguments when present; every other
// string/number/bool argument becomes a --flag. forced entries are appended
// last as --flags regardless of caller input (used to pin --data-source local
// for search-local). --agent is appended so the CLI emits machine JSON.
func makeCLITool(commandPath, positionals []string, forced map[string]string) server.ToolHandlerFunc {
	binPath, lookupErr := cobratree.SiblingCLIPath()
	posSet := make(map[string]bool, len(positionals))
	for _, p := range positionals {
		posSet[p] = true
	}
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		if lookupErr != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("companion CLI binary not found: %v\nTried sibling lookup, NOTION_CLI_PATH, and PATH.", lookupErr)), nil
		}
		args := req.GetArguments()
		final := append([]string{}, commandPath...)
		for _, p := range positionals {
			if v, ok := args[p]; ok {
				if s := fmt.Sprintf("%v", v); s != "" {
					final = append(final, s)
				}
			}
		}
		keys := make([]string, 0, len(args))
		for k := range args {
			if posSet[k] {
				continue
			}
			if _, isForced := forced[k]; isForced {
				continue
			}
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			switch v := args[k].(type) {
			case bool:
				if v {
					final = append(final, "--"+k)
				}
			case float64:
				final = append(final, "--"+k, strconv.FormatFloat(v, 'f', -1, 64))
			case string:
				if v != "" {
					final = append(final, "--"+k, v)
				}
			default:
				if v != nil {
					final = append(final, "--"+k, fmt.Sprintf("%v", v))
				}
			}
		}
		fkeys := make([]string, 0, len(forced))
		for k := range forced {
			fkeys = append(fkeys, k)
		}
		sort.Strings(fkeys)
		for _, k := range fkeys {
			final = append(final, "--"+k, forced[k])
		}
		final = append(final, "--agent")
		out, err := cobratree.RunCLICommand(ctx, binPath, final)
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}
		return mcplib.NewToolResultText(out), nil
	}
}

// handleDuplicatePage implements the compound page-duplicate workflow Notion's
// REST API has no single endpoint for: fetch the source page (parent +
// properties) and its full block tree, then create a new page with the copied
// content. Read-only fields (id, timestamps, has_children, archived) are
// stripped from each block so the create call accepts them.
func handleDuplicatePage(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	pageID, _ := args["page_id"].(string)
	if pageID == "" {
		return mcplib.NewToolResultError("page_id is required"), nil
	}
	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	pageRaw, err := c.Get(ctx, "/v1/pages/"+pageID, nil)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	var page struct {
		Parent     json.RawMessage `json:"parent"`
		Properties json.RawMessage `json:"properties"`
	}
	if err := json.Unmarshal(pageRaw, &page); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("parsing source page: %v", err)), nil
	}

	body := map[string]any{}
	// Target parent: explicit override, else the source page's parent.
	if p, ok := args["parent"]; ok && fmt.Sprintf("%v", p) != "" {
		body["parent"] = p
	} else if len(page.Parent) > 0 {
		var parent any
		_ = json.Unmarshal(page.Parent, &parent)
		body["parent"] = parent
	}
	if len(page.Properties) > 0 {
		var props any
		_ = json.Unmarshal(page.Properties, &props)
		body["properties"] = props
	}

	children, err := copyBlockChildren(ctx, c, pageID)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	if len(children) > 0 {
		body["children"] = children
	}

	data, _, err := c.PostWithParams(ctx, "/v1/pages", map[string]string{}, body)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

// copyBlockChildren recursively fetches the block tree under parentID and
// returns create-ready block payloads (read-only fields stripped, nested
// children inlined under "children"). Block types Notion rejects on append
// (child_page, child_database, unsupported) are skipped.
func copyBlockChildren(ctx context.Context, c *client.Client, parentID string) ([]map[string]any, error) {
	var out []map[string]any
	cursor := ""
	for {
		params := map[string]string{"page_size": "100"}
		if cursor != "" {
			params["start_cursor"] = cursor
		}
		raw, err := c.Get(ctx, "/v1/blocks/"+parentID+"/children", params)
		if err != nil {
			return nil, err
		}
		var resp struct {
			Results    []map[string]any `json:"results"`
			HasMore    bool             `json:"has_more"`
			NextCursor string           `json:"next_cursor"`
		}
		if err := json.Unmarshal(raw, &resp); err != nil {
			return nil, err
		}
		for _, blk := range resp.Results {
			btype, _ := blk["type"].(string)
			switch btype {
			case "", "child_page", "child_database", "unsupported":
				continue
			}
			clean := map[string]any{"object": "block", "type": btype}
			if payload, ok := blk[btype].(map[string]any); ok {
				delete(payload, "children")
				clean[btype] = payload
			}
			if hasChildren, _ := blk["has_children"].(bool); hasChildren {
				if id, _ := blk["id"].(string); id != "" {
					kids, err := copyBlockChildren(ctx, c, id)
					if err != nil {
						return nil, err
					}
					if len(kids) > 0 {
						if payload, ok := clean[btype].(map[string]any); ok {
							payload["children"] = kids
						}
					}
				}
			}
			out = append(out, clean)
		}
		if !resp.HasMore || resp.NextCursor == "" {
			break
		}
		cursor = resp.NextCursor
	}
	return out, nil
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export NOTION_BEARER_AUTH=<your-key>" +
					"\n      Run 'notion-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export NOTION_BEARER_AUTH=<your-key>" +
					"\n      Run 'notion-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export NOTION_BEARER_AUTH=<your-key>" +
					"\n      Run 'notion-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "notion-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "notion-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer func() { _ = db.Close() }()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer func() { _ = db.Close() }()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer func() { _ = rows.Close() }()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "notion",
		"description": "Combined CLI for multiple API services",
		"archetype":   "content",
		// typed_tool_count is the number of typed endpoint + framework + named
		// magic-moment + REST-parity tools declared in this file (10 endpoint +
		// 3 framework + 7 magic-moment + 11 parity). The live tool surface is
		// larger still because the runtime Cobra-tree mirror (RegisterAll)
		// registers a shell-out tool for remaining user-facing CLI commands
		// (format preview/append/sql, workflow status, import). Call tools/list
		// for the authoritative count.
		"typed_tool_count": 31,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools, named magic-moment tools (format-write-page/format-update-block/format-read-page/sync-database/sync-page/search-local/workflow-run), Notion REST parity tools (databases-*, comments-*, users-*, pages-move, pages-duplicate), plus a runtime mirror of the remaining user-facing CLI commands. Call tools/list for the full list.",
		// unique_capabilities is the parity signal: it names what this CLI does
		// that the official Notion MCP does not, so an agent choosing a server
		// can tell the two apart. The official MCP renders writes through plain
		// markdown and drops block-level color and per-run annotations; this
		// CLI preserves them.
		"unique_capabilities": []map[string]any{
			{
				"name":        "extended-markdown color & annotation writer",
				"commands":    []string{"format preview", "format append", "format write-page", "format update"},
				"description": "Write and re-style Notion blocks with full block-level color and per-run annotation fidelity (bold/italic/underline/strike/code, text and background colors, callout icons) that the official Notion MCP drops. Dialect adds {color:text}, {color_bg:text}, and trailing {color= bg= icon=} attribute groups on top of standard markdown.",
			},
			{
				"name":        "annotation-aware local mirror + SQL",
				"commands":    []string{"format mirror", "format sql"},
				"description": "Mirror a page's block tree into local SQLite with per-run color/annotation columns, then run read-only SQL over it (tables: pages, blocks, rich_text; views: colored_text, block_palette). Lets agents query formatting (e.g. find every red run) — not possible through the official MCP.",
			},
		},
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "NOTION_BEARER_AUTH",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "blocks",
				"description": "Manage blocks",
				"endpoints":   []string{"delete", "retrieve", "update"},
				"searchable":  true,
			},
			{
				"name":        "children",
				"description": "Manage children",
				"endpoints":   []string{"retrieve-block", "update-block"},
				"searchable":  true,
			},
			{
				"name":        "notion-search",
				"description": "Manage notion search",
				"endpoints":   []string{"search"},
				"searchable":  true,
			},
			{
				"name":        "pages",
				"description": "Manage pages",
				"endpoints":   []string{"create", "retrieve", "update", "move", "duplicate"},
				"searchable":  true,
			},
			{
				"name":        "databases",
				"description": "Manage databases (Notion REST parity)",
				"endpoints":   []string{"create", "retrieve", "update", "query"},
				"searchable":  true,
			},
			{
				"name":        "comments",
				"description": "Manage comments (Notion REST parity)",
				"endpoints":   []string{"list", "create"},
				"searchable":  false,
			},
			{
				"name":        "users",
				"description": "Manage users (Notion REST parity)",
				"endpoints":   []string{"list", "retrieve", "me"},
				"searchable":  false,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the page_size parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
