// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBlocksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "blocks",
		Short:  "Get, update, and delete blocks",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBlocksDeleteCmd(flags))
	cmd.AddCommand(newBlocksRetrieveCmd(flags))
	cmd.AddCommand(newBlocksUpdateCmd(flags))
	return cmd
}
