// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newChildrenCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "children",
		Short:  "Get and update children",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newChildrenRetrieveBlockCmd(flags))
	cmd.AddCommand(newChildrenUpdateBlockCmd(flags))
	return cmd
}
