// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPagesPropertiesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "properties",
		Short: "Get properties for pages",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPagesPropertiesRetrievePagePropertyCmd(flags))
	return cmd
}
